### ISSUE TITLE
Version 0.0.12 - Youtube videos being posted thru "Select Youtube Video" feature doesn't play 

### ISSUE THREAD

**Issue by josephace135** [hapramp/1Rramp-Android#132]
#### Expected behavior
Youtube video that is included in publishing a “Post” should play when tapped and viewed, both in app or any front-end (Steemit.com or busy.org).

#### Actual behavior
Youtube video that is being selected and published as a “Post” doesn’t play when tapped and viewed -
 for which it displays a “Video unavailable” message.
	
#### How to reproduce
* Tap the “`+`” icon that is found at the bottom center of the app and tap the “Post” button.
* Tap the “Select Youtube Video” feature.
* Input the keyword of the Youtube video you intend to include in your post and enter.
* Tap the video you desire to include and select whichever community that suits the video.
* Tap “Publish” button.
* After a successful posting, tap thr “Profile” button and wait for your posts to load.
* Tap the post you created a while ago and tap the “Play” button found at the middle center of the iframe designated for the Youtube video.
* The issue occurs for which it says “Video unavailable”. Additionally, the same message appears too when viewing the post in Steemit front end whereas in busy.org front-end the iframe is not displayed.

For Steemit front-end:
![steemit video unavailable](https://user-images.githubusercontent.com/35374763/44994211-285c5c00-afd0-11e8-8bc3-5cffca018748.PNG)

For busy.org front-end:
![busy iframe not shown](https://user-images.githubusercontent.com/35374763/44994246-5772cd80-afd0-11e8-891f-5cc25b1b6d3c.PNG)

#### Environment
* App/Plugin version: HapRamp-Android v0.0.12
* Device: Samsung Galaxy J2 Prime (SM-G532G/DS)
* Operating system: Android version 6.0.1

#### Recording Of The Bug
https://www.youtube.com/watch?v=o1P-e010IcA

**Comment by josephace135** [comment]
Video is still unavailable in latest version 0.0.13.

**Comment by singhpratyush** [comment]
@josephace135 Please provide the link to the post which is failing.

**Comment by josephace135** [comment]
@singhpratyush this one - https://steemit.com/hapramp/@froeilanddave/p1g7abkzw2o8cfcd53c4aq6kqb5vo9aquqbkwqn00vc6yo13dinlrkqcwb5zuqsq20180903225032

**Comment by bxute** [comment]
@josephace135 @singhpratyush This issue is with youtube embed url.
Actually, we are using `youtube.com/embed/<video-id>`.
This URL is not working for any video on the browser even. We need to find an alternative to embed it.

Cross check:
Original video: https://www.youtube.com/watch?v=pZ0viMxYDA4
Embed link:  https://www.youtube.com/embed/pZ0viMxYDA4

**Comment by singhpratyush** [comment]
@bxute That's not the case.

This can be fixed by simply changing `http` to `https` at https://github.com/hapramp/1Rramp-Android/blob/0d79388a211c848af25a433c8bfa8e513dbf033b/app/src/main/java/com/hapramp/views/post/PostCreateComponent.java#L224.

I've checked the embed URL you mentioned and it is now working.

**Comment by josephace135** [comment]
I tried following @singhpratyush 's proposed fix of changing `http` to `https`., the youtube video works fine upon that change, @bxute.

**Comment by singhpratyush** [comment]
@josephace135: It was the `https` issue - thanks a lot for reporting the bug :)
